import { useMemo, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, LockKeyhole, Plus, Scale, Search } from "lucide-react";
import { auditSessions, items } from "../data/fixtures";
import { openContainerContent, reconcile } from "../domain/calculations";
import { useApp } from "../context/AppContext";
import { money, number } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Progress, Select, StatCard, TableShell } from "../components/ui";

export function AuditsPage() {
  return <div className="page-grid"><PageHeader eyebrow="Audit sessions" title="Count, explain, and close with confidence" description="Each session connects two physical boundaries with all posted activity in between." actions={<Link to="/audits/new"><Button><Plus className="size-4" />Start audit</Button></Link>} /><Card><TableShell><table className="data-table"><thead><tr><th>Session</th><th>Cutoff</th><th>Progress</th><th>Owner</th><th>Status</th><th /></tr></thead><tbody>{auditSessions.map((audit) => <tr key={audit.id}><td><strong>{audit.name}</strong><small className="block text-slate-500">{audit.id}</small></td><td>{audit.cutoff}</td><td><div className="min-w-32"><div className="mb-1 flex justify-between text-xs"><span>{audit.progress}%</span><span>{audit.progress === 100 ? "Complete" : "43 / 60"}</span></div><Progress value={audit.progress} /></div></td><td>{audit.owner}</td><td><Badge tone={audit.status === "Closed" ? "success" : "info"}>{audit.status}</Badge></td><td><Link to={`/audits/${audit.id}`} aria-label={`Open ${audit.name}`}><ArrowRight className="size-4 text-slate-400" /></Link></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function NewAuditPage() {
  const navigate = useNavigate();
  return <div className="mx-auto max-w-4xl page-grid"><Link to="/audits" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Audit sessions</Link><PageHeader eyebrow="New audit" title="Prepare the count scope" description="The item list and measurement profiles are snapshotted when counting starts." /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Session name</span><Input defaultValue="July 5 Weekly Audit" /></label><label><span className="field-label">Site</span><Select className="w-full"><option>BGC Flagship</option></Select></label><label><span className="field-label">Cutoff</span><Input type="datetime-local" defaultValue="2026-07-05T23:59" /></label><label><span className="field-label">Count order</span><Select className="w-full"><option>Location, then category</option><option>Category, then item name</option></Select></label><label className="sm:col-span-2"><span className="field-label">Scope</span><div className="grid gap-3 sm:grid-cols-4">{["Beverage","Food","Supplies","Assets"].map((scope) => <label key={scope} className="flex items-center gap-2 rounded-lg border p-3 text-sm font-medium"><input type="checkbox" defaultChecked={scope !== "Assets"} />{scope}</label>)}</div></label></div><div className="flex justify-end gap-2 border-t p-5"><Button variant="secondary" onClick={() => navigate("/audits")}>Cancel</Button><Button onClick={() => navigate("/audits/AUD-2026-0705/count")}>Create count sheet <ArrowRight className="size-4" /></Button></div></Card></div>;
}

const steps = [
  ["Overview", ""], ["Count", "count"], ["Review", "review"], ["Reconcile", "reconcile"], ["Report", "report"]
];

function AuditNav() {
  const location = useLocation();
  return <div className="flex overflow-x-auto rounded-xl border bg-white p-1">{steps.map(([label, suffix], index) => { const to = `/audits/AUD-2026-0628${suffix ? `/${suffix}` : ""}`; const active = suffix ? location.pathname.endsWith(suffix) : /AUD-2026-0628$/.test(location.pathname); return <Link key={label} to={to} className={`flex min-w-28 flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${active ? "bg-brand-600 text-white" : "text-slate-500 hover:bg-slate-50"}`}><span className={`grid size-5 place-items-center rounded-full text-[10px] ${active ? "bg-white/20" : "bg-slate-100"}`}>{index + 1}</span>{label}</Link>; })}</div>;
}

export function AuditWorkspace() {
  const location = useLocation();
  const section = location.pathname.split("/").pop();
  return <div className="page-grid"><div><Link to="/audits" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Audit sessions</Link><div className="mt-4"><PageHeader eyebrow="AUD-2026-0628" title="June 28 Weekly Audit" description="BGC Flagship · Cutoff Jun 28, 11:59 PM · Previous boundary Jun 21" /></div></div><AuditNav />{section === "count" ? <CountSheet /> : section === "review" ? <AuditReview /> : section === "reconcile" ? <AuditReconcile /> : section === "report" ? <AuditReport /> : <AuditSummary />}</div>;
}

function AuditSummary() {
  return <><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Count completion" value="72%" detail="43 of 60 items" tone="info" /><StatCard label="Exceptions" value="5" detail="2 missing · 3 unusual" tone="warning" /><StatCard label="Draft variance" value={money(-1840)} detail="2.0% of explained usage" tone="danger" /></div><div className="grid gap-5 lg:grid-cols-[1fr_0.6fr]"><Card><CardHeader title="Count by location" description="Continue where the team left off." /><div className="divide-y">{[["Main Bar",96],["Dry Store",82],["Cold Store",54],["Kitchen Prep",41]].map(([name, value]) => <div key={name} className="p-5"><div className="mb-2 flex justify-between text-sm"><strong>{name}</strong><span>{value}%</span></div><Progress value={Number(value)} /></div>)}</div></Card><Card><CardHeader title="Next best action" description="Highest-impact step for this session." /><div className="p-5"><div className="grid size-11 place-items-center rounded-xl bg-amber-100 text-amber-700"><AlertTriangle /></div><h3 className="mt-4 text-lg font-bold">Finish Cold Store counts</h3><p className="mt-2 text-sm leading-6 text-slate-500">Nine food items remain uncounted. Reconciliation stays provisional until all scoped items are resolved.</p><Link to="/audits/AUD-2026-0628/count"><Button className="mt-5 w-full">Continue counting</Button></Link></div></Card></div></>;
}

function CountSheet() {
  const { countLines, updateCount, notify } = useApp();
  const [search, setSearch] = useState("");
  const visible = items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase()));
  const counted = Object.keys(countLines).length;
  return <><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Progress" value={`${counted || 43} / 60`} detail="Autosaved in this prototype" tone="info" /><StatCard label="Current area" value="Main Bar" detail="Spirits · alphabetical" /><StatCard label="Warnings" value="2" detail="Values need review" tone="warning" /></div><Card><div className="flex flex-wrap items-center gap-3 border-b p-4"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Find an item…" /></div><Select><option>Main Bar</option><option>Dry Store</option><option>Cold Store</option></Select><Badge tone="success">Draft autosaved</Badge></div><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Package</th><th>Full / units</th><th>Scale weight</th><th>Computed open</th><th>Status</th></tr></thead><tbody>{visible.map((item) => { const line = countLines[item.id]; const calculation = item.tare && line?.scaleWeight ? openContainerContent(line.scaleWeight, item.tare, item.factor ?? 1, item.capacity) : null; return <tr key={item.id}><td><strong>{item.name}</strong><small className="block text-slate-500">{item.location}</small></td><td>{item.package}</td><td><Input aria-label={`${item.name} full count`} type="number" min="0" className="w-24" value={line?.full ?? ""} onChange={(event) => updateCount({ itemId: item.id, full: Number(event.target.value), scaleWeight: line?.scaleWeight })} placeholder="0" /></td><td>{item.tare ? <div className="relative w-32"><Scale className="absolute left-2.5 top-3 size-4 text-slate-400" /><Input aria-label={`${item.name} scale weight`} type="number" className="pl-8" value={line?.scaleWeight ?? ""} onChange={(event) => updateCount({ itemId: item.id, full: line?.full ?? 0, scaleWeight: Number(event.target.value) })} placeholder={`${item.tare} g`} /></div> : <span className="text-slate-400">Not used</span>}</td><td>{calculation ? <><strong>{number(calculation.value)} ml</strong>{calculation.warning ? <small className="block text-red-600">{calculation.warning}</small> : null}</> : "—"}</td><td><Badge tone={line ? calculation?.warning ? "danger" : "success" : "neutral"}>{line ? calculation?.warning ? "Review" : "Counted" : "Not counted"}</Badge></td></tr>; })}</tbody></table></TableShell><div className="flex justify-end gap-2 border-t p-4"><Button variant="secondary" onClick={() => notify("Count draft saved.")}>Save draft</Button><Link to="/audits/AUD-2026-0628/review"><Button>Review count <ArrowRight className="size-4" /></Button></Link></div></Card></>;
}

function AuditReview() {
  const issues = [["Dark Rum","Computed open content exceeds the expected change by 28%.","Unusual"],["Beef Tenderloin","No count recorded for Cold Store.","Missing"],["Food-safe Sanitizer","Measurement profile changed after the previous audit.","Profile"],["Highball Glass","Count decreased by 18 pieces with no breakage record.","Unusual"]];
  return <><Notice title="Review before reconciliation" tone="warning">Four exceptions need confirmation. Resolving an exception explains the evidence; it does not silently change the count.</Notice><Card><CardHeader title="Count exceptions" description="Prioritized by likely value and audit impact." /><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Issue</th><th>Type</th><th>Resolution</th></tr></thead><tbody>{issues.map(([name, issue, type]) => <tr key={name}><td className="font-semibold">{name}</td><td>{issue}</td><td><Badge tone={type === "Missing" ? "danger" : "warning"}>{type}</Badge></td><td><Select aria-label={`Resolve ${name}`}><option>Needs action</option><option>Count confirmed</option><option>Recount requested</option><option>Documented exception</option></Select></td></tr>)}</tbody></table></TableShell><div className="flex justify-end border-t p-4"><Link to="/audits/AUD-2026-0628/reconcile"><Button>Continue to reconciliation <ArrowRight className="size-4" /></Button></Link></div></Card></>;
}

function AuditReconcile() {
  const result = reconcile({ beginning: 82400, receipts: 21400, ending: 10000, sales: 48200, recipeUse: 33400, nonRevenue: 4200, waste: 6160 });
  const rows = [["London Dry Gin",12800,12450,350],["Dark Rum",9420,7850,1570],["Fresh Lime",5200,5150,50],["Beef Tenderloin",11300,11880,-580],["Other items",65080,64850,230]];
  return <><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Physical depletion" value={money(result.physical)} detail="Beginning + receipts − ending" /><StatCard label="Explained depletion" value={money(result.explained)} detail="Sales + recipes + non-revenue + waste" tone="success" /><StatCard label="Unexplained variance" value={money(result.variance)} detail={`${number((result.variance / result.physical) * 100)}% of physical depletion`} tone="danger" /></div><Card><CardHeader title="Variance by item" description="Select an item to trace every count and movement." /><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Physical</th><th>Explained</th><th>Variance</th><th>Status</th></tr></thead><tbody>{rows.map(([name, physical, explained, variance]) => <tr key={name}><td className="font-semibold">{name}</td><td>{money(Number(physical))}</td><td>{money(Number(explained))}</td><td className={Number(variance) > 500 ? "font-semibold text-red-600" : ""}>{money(Number(variance))}</td><td><Badge tone={Math.abs(Number(variance)) > 500 ? "danger" : "success"}>{Math.abs(Number(variance)) > 500 ? "Investigate" : "Within threshold"}</Badge></td></tr>)}</tbody></table></TableShell><div className="flex justify-end border-t p-4"><Link to="/audits/AUD-2026-0628/report"><Button>Prepare final report <ArrowRight className="size-4" /></Button></Link></div></Card></>;
}

function AuditReport() {
  const { role, notify } = useApp();
  return <><Notice title="Draft report">This report is recalculated from the session snapshot and posted activity. Closing creates an immutable report version.</Notice><div className="grid gap-4 sm:grid-cols-4"><StatCard label="Beginning value" value={money(82400)} detail="Jun 21 closed count" /><StatCard label="Purchases" value={money(21400)} detail="12 posted receipts" /><StatCard label="Ending value" value={money(10000)} detail="Jun 28 count" /><StatCard label="Variance" value={money(1840)} detail="Requires explanation" tone="danger" /></div><Card><CardHeader title="Full Audit Report" description="Unified report · Beverage saved view" action={<div className="flex gap-2"><Button variant="secondary">Excel</Button><Button variant="secondary">PDF</Button></div>} /><div className="p-5"><div className="grid gap-4 sm:grid-cols-4">{[["Beginning",82400],["+ Receipts",21400],["− Ending",-10000],["Physical usage",93800]].map(([label,value]) => <div key={label} className="rounded-lg bg-slate-50 p-4"><span className="text-xs text-slate-500">{label}</span><strong className="mt-1 block">{money(Number(value))}</strong></div>)}</div><div className="mt-5 rounded-xl border p-5"><div className="flex justify-between"><span>Explained activity</span><strong>{money(91960)}</strong></div><div className="mt-3 flex justify-between border-t pt-3 text-red-700"><span>Unexplained variance</span><strong>{money(1840)}</strong></div></div></div><div className="flex items-center justify-between border-t p-5"><p className="text-sm text-slate-500">{role === "owner" ? "Closing requires an Owner reason and records the current report version." : "Only an Owner can close this session."}</p><Button disabled={role !== "owner"} onClick={() => notify("Audit close request sent to approvals.")}><LockKeyhole className="size-4" />Request close</Button></div></Card></>;
}
