import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, GitBranch, Plus, Scale, Search, Truck, Utensils } from "lucide-react";
import { items } from "../data/fixtures";
import { money } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Select, StatCard, TableShell } from "../components/ui";
import { useApp } from "../context/AppContext";

const recipes = [
  { id: "gin-sour", name: "House Gin Sour", version: "v4", ingredients: 5, cost: 112.4, price: 360, status: "Published" },
  { id: "beef-special", name: "Chef Beef Special", version: "v2", ingredients: 8, cost: 288.6, price: 720, status: "Published" },
  { id: "rum-highball", name: "Dark Rum Highball", version: "Draft", ingredients: 4, cost: 98.2, price: 320, status: "Review" }
];
const suppliers = [
  { id: "metro", name: "Metro Beverage Supply", categories: "Spirits, mixers", last: "Jun 27", reliability: "98%", status: "Active" },
  { id: "fresh", name: "Fresh Fields Produce", categories: "Produce, dairy", last: "Jun 26", reliability: "91%", status: "Review" },
  { id: "prime", name: "Prime Cut Foods", categories: "Meat, poultry", last: "Jun 25", reliability: "96%", status: "Active" }
];

export function ItemsPage() {
  return <div className="page-grid"><PageHeader eyebrow="Catalog" title="Items" description="One universal catalog for beverages, food, supplies, and assets." actions={<Link to="/catalog/items/new"><Button><Plus className="size-4" />New item</Button></Link>} /><Card><div className="flex gap-3 border-b p-4"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><Input className="pl-9" placeholder="Search catalog…" /></div><Link to="/catalog/units"><Button variant="secondary"><Scale className="size-4" />Units</Button></Link></div><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Type</th><th>Category</th><th>Base unit</th><th>Package</th><th>Cost</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`/catalog/items/${item.id}`} className="font-semibold text-brand-600">{item.name}</Link><small className="block text-slate-500">{item.sku}</small></td><td>{item.kind}</td><td>{item.category}</td><td>{item.baseUnit}</td><td>{item.package}</td><td>{money(item.cost)}</td><td><Badge tone={item.status === "Review" ? "warning" : "success"}>{item.status === "Review" ? "Review profile" : "Active"}</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function ItemEditor() {
  const { itemId } = useParams();
  const navigate = useNavigate();
  const { notify } = useApp();
  const item = items.find((row) => row.id === itemId);
  return <div className="mx-auto max-w-5xl page-grid"><Link to="/catalog/items" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Items</Link><PageHeader eyebrow={item ? item.sku : "New catalog item"} title={item?.name ?? "Create an item"} description="Configure ordinary fields first. Advanced measurement appears only when needed." /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Item name</span><Input defaultValue={item?.name} placeholder="Descriptive inventory name" /></label><label><span className="field-label">SKU</span><Input defaultValue={item?.sku} placeholder="Generated if empty" /></label><label><span className="field-label">Item type</span><Select className="w-full" defaultValue={item?.kind}><option>Beverage</option><option>Food</option><option>Supply</option><option>Asset</option></Select></label><label><span className="field-label">Category</span><Input defaultValue={item?.category} /></label><label><span className="field-label">Base unit</span><Select className="w-full" defaultValue={item?.baseUnit}><option>ml</option><option>kg</option><option>L</option><option>pc</option></Select></label><label><span className="field-label">Package</span><Input defaultValue={item?.package} placeholder="e.g. 700 ml bottle" /></label><label><span className="field-label">Default cost</span><Input type="number" defaultValue={item?.cost} /></label><label><span className="field-label">Par level</span><Input type="number" defaultValue={item?.par} /></label></div><div className="border-t p-6"><h2 className="font-semibold">Measurement profile</h2><p className="mt-1 text-sm text-slate-500">Required only for weighed containers or item-specific conversions.</p><div className="mt-4 grid gap-4 sm:grid-cols-3"><label><span className="field-label">Tare weight (g)</span><Input type="number" defaultValue={item?.tare} /></label><label><span className="field-label">Content factor</span><Input type="number" step="0.01" defaultValue={item?.factor} /></label><label><span className="field-label">Capacity</span><Input type="number" defaultValue={item?.capacity} /></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => navigate("/catalog/items")}>Cancel</Button><Button onClick={() => { notify("Catalog item saved."); navigate("/catalog/items"); }}>Save item</Button></div></div></Card></div>;
}

export function UnitsPage() {
  return <div className="page-grid"><PageHeader eyebrow="Catalog" title="Units and conversions" description="Generic conversions stay within one dimension. Product-specific profiles handle cross-dimension measurements." actions={<Button><Plus className="size-4" />New unit</Button>} /><Notice title="Conversion safety">FNB/LIS will not globally convert weight to volume. A liquid or packaged item must supply its own validated factor.</Notice><Card><CardHeader title="Configured units" description="Shared definitions for all item types." /><TableShell><table className="data-table"><thead><tr><th>Unit</th><th>Dimension</th><th>Base conversion</th><th>Used by</th><th>Status</th></tr></thead><tbody>{[["milliliter","Volume","1 ml","42 items"],["liter","Volume","1,000 ml","16 items"],["gram","Mass","1 g","34 items"],["kilogram","Mass","1,000 g","28 items"],["piece","Count","1 pc","51 items"],["case","Package","Item-specific","19 items"]].map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={cell} className={index === 0 ? "font-semibold" : ""}>{cell}</td>)}<td><Badge tone="success">Active</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function RecipesPage() {
  return <div className="page-grid"><PageHeader eyebrow="Recipes and BOMs" title="Recipes" description="Published versions preserve historical ingredient use while new versions improve future work." actions={<Link to="/recipes/new"><Button><Plus className="size-4" />New recipe</Button></Link>} /><Card><TableShell><table className="data-table"><thead><tr><th>Recipe</th><th>Version</th><th>Ingredients</th><th>Cost</th><th>Selling price</th><th>Food cost</th><th>Status</th></tr></thead><tbody>{recipes.map((row) => <tr key={row.id}><td><Link to={`/recipes/${row.id}`} className="font-semibold text-brand-600">{row.name}</Link></td><td>{row.version}</td><td>{row.ingredients}</td><td>{money(row.cost)}</td><td>{money(row.price)}</td><td>{Math.round((row.cost / row.price) * 100)}%</td><td><Badge tone={row.status === "Published" ? "success" : "warning"}>{row.status}</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function RecipeEditor() {
  const { recipeId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const recipe = recipes.find((row) => row.id === recipeId);
  const versions = location.pathname.endsWith("/versions");
  if (versions) return <div className="page-grid"><Link to={`/recipes/${recipeId}`} className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />{recipe?.name}</Link><PageHeader eyebrow="Version history" title={recipe?.name ?? "Recipe"} description="Published versions are immutable and remain linked to historical sales." /><Card><TableShell><table className="data-table"><thead><tr><th>Version</th><th>Effective date</th><th>Cost</th><th>Published by</th><th>Status</th></tr></thead><tbody>{[["v4","Jun 15, 2026","₱112.40","Lourd Borromeo","Current"],["v3","Mar 2, 2026","₱108.20","Mia Santos","Superseded"],["v2","Jan 8, 2026","₱102.90","Lourd Borromeo","Superseded"]].map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={cell} className={index === 0 ? "font-semibold" : ""}>{cell}</td>)}</tr>)}</tbody></table></TableShell></Card></div>;
  return <div className="mx-auto max-w-5xl page-grid"><Link to="/recipes" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Recipes</Link><PageHeader eyebrow={recipe?.version ?? "New recipe"} title={recipe?.name ?? "Create a recipe"} description="Build from base quantities so sales expand deterministically." actions={recipe ? <Link to={`/recipes/${recipe.id}/versions`}><Button variant="secondary"><GitBranch className="size-4" />Versions</Button></Link> : undefined} /><Card><div className="grid gap-4 p-5 sm:grid-cols-3"><label className="sm:col-span-2"><span className="field-label">Recipe name</span><Input defaultValue={recipe?.name} /></label><label><span className="field-label">Selling price</span><Input type="number" defaultValue={recipe?.price} /></label></div><TableShell><table className="data-table"><thead><tr><th>Ingredient</th><th>Quantity</th><th>Unit</th><th>Cost contribution</th></tr></thead><tbody>{items.slice(0,4).map((item,index) => <tr key={item.id}><td className="font-semibold">{item.name}</td><td><Input className="w-24" type="number" defaultValue={[45,15,0.03,0.12][index]} /></td><td>{item.baseUnit}</td><td>{money(item.cost / (index + 5))}</td></tr>)}</tbody></table></TableShell><div className="flex justify-between border-t p-5"><div><span className="text-sm text-slate-500">Estimated cost</span><strong className="ml-3">{money(recipe?.cost ?? 112.4)}</strong></div><Button onClick={() => navigate("/recipes")}>Publish version</Button></div></Card></div>;
}

export function SuppliersPage() {
  return <div className="page-grid"><PageHeader eyebrow="Partners" title="Suppliers" description="Products, aliases, receiving history, and reliability in one place." actions={<Link to="/suppliers/new"><Button><Plus className="size-4" />New supplier</Button></Link>} /><Card><TableShell><table className="data-table"><thead><tr><th>Supplier</th><th>Categories</th><th>Last receipt</th><th>Reliability</th><th>Status</th></tr></thead><tbody>{suppliers.map((row) => <tr key={row.id}><td><Link to={`/suppliers/${row.id}`} className="font-semibold text-brand-600">{row.name}</Link></td><td>{row.categories}</td><td>{row.last}</td><td>{row.reliability}</td><td><Badge tone={row.status === "Active" ? "success" : "warning"}>{row.status}</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function SupplierEditor() {
  const { supplierId } = useParams();
  const supplier = suppliers.find((row) => row.id === supplierId);
  return <div className="mx-auto max-w-4xl page-grid"><Link to="/suppliers" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Suppliers</Link><PageHeader eyebrow={supplier ? "Supplier profile" : "New supplier"} title={supplier?.name ?? "Create a supplier"} description="Private terms remain permission-controlled and excluded from telemetry." /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Supplier name</span><Input defaultValue={supplier?.name} /></label><label><span className="field-label">Categories</span><Input defaultValue={supplier?.categories} /></label><label><span className="field-label">Contact email</span><Input type="email" defaultValue="orders@example.test" /></label><label><span className="field-label">Delivery cadence</span><Select className="w-full"><option>Weekly</option><option>Twice weekly</option><option>On demand</option></Select></label></div><div className="flex justify-end border-t p-5"><Button><Truck className="size-4" />Save supplier</Button></div></Card></div>;
}
