import { useRef, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, CheckCircle2, FileSpreadsheet, FileUp, Link2, ShieldCheck } from "lucide-react";
import { useApp } from "../context/AppContext";
import { money } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Progress, Select, StatCard, TableShell } from "../components/ui";

export function ImportsPage() {
  return <div className="page-grid"><PageHeader eyebrow="Ingestion" title="Imports" description="Uploaded data stays staged until review and approval. Extraction never changes inventory directly." actions={<Link to="/imports/new"><Button><FileUp className="size-4" />Upload file</Button></Link>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Ready to commit" value="1" detail="IMP-307 · supplier receipt" tone="success" /><StatCard label="Needs mapping" value="2 rows" detail="IMP-308 · POS daily close" tone="warning" /><StatCard label="Committed this month" value="18" detail="2,840 normalized rows" /></div><Card><CardHeader title="Import batches" description="Original files, mappings, approvals, and journal results remain linked." /><TableShell><table className="data-table"><thead><tr><th>Batch</th><th>Source</th><th>Type</th><th>Rows</th><th>Uploaded by</th><th>Status</th></tr></thead><tbody><tr><td><Link className="font-semibold text-brand-600" to="/imports/IMP-308/review">IMP-308</Link></td><td>POS_Daily_Close_0628.xlsx</td><td>Sales</td><td>146</td><td>Carlo Reyes</td><td><Badge tone="warning">Needs review</Badge></td></tr><tr><td className="font-semibold">IMP-307</td><td>Metro_Beverage_INV1048.csv</td><td>Purchase</td><td>8</td><td>Mia Santos</td><td><Badge tone="success">Committed</Badge></td></tr><tr><td className="font-semibold">IMP-306</td><td>June21_Audit.pdf</td><td>Audit</td><td>60</td><td>Lourd Borromeo</td><td><Badge tone="info">Archived</Badge></td></tr></tbody></table></TableShell></Card></div>;
}

export function NewImportPage() {
  const navigate = useNavigate();
  const input = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState("");
  return <div className="mx-auto max-w-3xl page-grid"><Link to="/imports" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Imports</Link><PageHeader eyebrow="New import" title="Upload source data" description="CSV and Excel use deterministic parsing first. PDF and images may use reviewed extraction." /><Card className="p-6"><label><span className="field-label">Transaction category</span><Select className="w-full"><option>Sales</option><option>Purchase</option><option>Audit count</option><option>Non-revenue</option></Select></label><button type="button" onClick={() => input.current?.click()} className="mt-5 grid min-h-64 w-full place-items-center rounded-xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center hover:border-blue-400 hover:bg-blue-50"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-white text-brand-600 shadow-sm"><FileSpreadsheet /></span><strong className="mt-4 block">{file || "Choose a file or drag it here"}</strong><p className="mt-2 text-sm text-slate-500">CSV, XLSX, PDF, PNG, or JPG · maximum 25 MB</p></div></button><input ref={input} className="hidden" type="file" onChange={(event) => setFile(event.target.files?.[0]?.name ?? "")} /><Notice title="Privacy and safety">Files are validated, tenant-scoped, and never sent to analytics. AI extraction is staging-only.</Notice><div className="mt-5 flex justify-end"><Button disabled={!file} onClick={() => navigate("/imports/IMP-308/review")}>Parse and review <ArrowRight className="size-4" /></Button></div></Card></div>;
}

export function ImportWorkspace() {
  const location = useLocation();
  const navigate = useNavigate();
  const { importRows, updateImportRow, importCommitted, commitImport, role } = useApp();
  const section = location.pathname.split("/").pop();
  const reviewCount = importRows.filter((row) => row.status === "Review").length;
  if (section === "summary" || importCommitted) return <div className="mx-auto max-w-3xl page-grid"><Link to="/imports" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Imports</Link><Card className="p-8 text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><CheckCircle2 className="size-8" /></span><h1 className="mt-5 text-3xl font-bold">Import committed</h1><p className="mt-2 text-slate-500">IMP-308 created one posted sales document and a traceable journal batch.</p><div className="mt-7 grid gap-3 text-left sm:grid-cols-3"><StatCard label="Rows" value="146" detail="144 automatic · 2 reviewed" /><StatCard label="Amount" value={money(48760)} detail="Source total preserved" /><StatCard label="Journal batch" value="JRN-8841" detail="Available in Audit Log" tone="success" /></div><Link to="/audit-log/LOG-8801"><Button className="mt-7">View audit evidence</Button></Link></Card></div>;
  return <div className="page-grid"><Link to="/imports" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Imports</Link><PageHeader eyebrow="IMP-308 · Sales" title={section === "mapping" ? "Resolve item mappings" : "Review extracted rows"} description="POS_Daily_Close_0628.xlsx · uploaded by Carlo Reyes · original file retained" actions={<Badge tone={reviewCount ? "warning" : "success"}>{reviewCount ? `${reviewCount} need review` : "Ready"}</Badge>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Rows" value="146" detail="Showing representative sample" /><StatCard label="Confidence" value="94%" detail="Weighted extraction confidence" tone="success" /><StatCard label="Source total" value={money(48760)} detail="Matches normalized total" /></div><Card><CardHeader title={section === "mapping" ? "Mapping workspace" : "Staged rows"} description="Changes here do not affect stock." /><TableShell><table className="data-table"><thead><tr><th>Source text</th><th>Matched item / recipe</th><th>Quantity</th><th>Amount</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{importRows.map((row) => <tr key={row.id}><td className="font-medium">{row.source}</td><td>{row.status === "Review" || section === "mapping" ? <Select value={row.matchedItem} onChange={(event) => updateImportRow(row.id,{ matchedItem: event.target.value, status: event.target.value === "Unmatched" ? "Review" : "Matched", confidence: 1 })}><option>Unmatched</option><option>Beef Tenderloin</option><option>House Gin Sour</option><option>Dark Rum</option></Select> : row.matchedItem}</td><td>{row.quantity} {row.unit}</td><td>{money(row.amount)}</td><td>{Math.round(row.confidence * 100)}%</td><td><Badge tone={row.status === "Matched" ? "success" : "warning"}>{row.status}</Badge></td></tr>)}</tbody></table></TableShell><div className="flex flex-wrap justify-between gap-3 border-t p-4"><Button variant="secondary" onClick={() => navigate("/imports/IMP-308/mapping")}><Link2 className="size-4" />Mapping workspace</Button><Button disabled={reviewCount > 0 || role !== "owner"} onClick={commitImport}><ShieldCheck className="size-4" />{role === "owner" ? "Approve and commit" : "Owner approval required"}</Button></div></Card></div>;
}
