import { useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRightLeft, ChevronRight, Download, History, PackagePlus, Search, SlidersHorizontal } from "lucide-react";
import { items } from "../data/fixtures";
import { money, number } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Select, StatCard, TableShell } from "../components/ui";
import { useApp } from "../context/AppContext";

const tone = (status: string) => status === "Healthy" || status === "Posted" ? "success" : status === "Low stock" ? "danger" : "warning";

export function InventoryPage() {
  const [search, setSearch] = useState("");
  const [kind, setKind] = useState("All");
  const visible = items.filter((item) => (kind === "All" || item.kind === kind) && `${item.name} ${item.sku} ${item.category}`.toLowerCase().includes(search.toLowerCase()));
  const total = items.reduce((sum, item) => sum + item.value, 0);
  return <div className="page-grid">
    <PageHeader eyebrow="Inventory" title="Stock on hand" description="Current projected balances by item and location, with every quantity traceable to its journal." actions={<><Button variant="secondary"><Download className="size-4" />Export view</Button><Link to="/inventory/actions/new"><Button><ArrowRightLeft className="size-4" />Stock action</Button></Link></>} />
    <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Inventory value" value={money(total)} detail="At current cost snapshots" tone="success" /><StatCard label="Low stock" value="2" detail="Dark Rum · Beef Tenderloin" tone="danger" /><StatCard label="Needs review" value="1" detail="Sanitizer measurement profile" tone="warning" /></div>
    <Card><div className="flex flex-wrap gap-3 border-b p-4"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search item, SKU, or category…" /></div><Select value={kind} onChange={(event) => setKind(event.target.value)}><option>All</option><option>Beverage</option><option>Food</option><option>Supply</option><option>Asset</option></Select><Button variant="secondary"><SlidersHorizontal className="size-4" />Filters</Button></div><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Category</th><th>Location</th><th>On hand</th><th>Value</th><th>Status</th><th /></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong className="block">{item.name}</strong><small className="text-slate-500">{item.sku} · {item.package}</small></td><td>{item.category}</td><td>{item.location}</td><td className="font-semibold">{number(item.onHand)} {item.baseUnit === "ml" ? "bottles eq." : item.baseUnit}</td><td>{money(item.value)}</td><td><Badge tone={tone(item.status)}>{item.status}</Badge></td><td><Link to={`/inventory/items/${item.id}`} aria-label={`View ${item.name}`}><ChevronRight className="size-4 text-slate-400" /></Link></td></tr>)}</tbody></table></TableShell></Card>
  </div>;
}

export function InventoryItemPage() {
  const { itemId } = useParams();
  const item = items.find((row) => row.id === itemId) ?? items[0];
  return <div className="page-grid">
    <Link to="/inventory" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Inventory</Link>
    <PageHeader eyebrow={`${item.kind} · ${item.category}`} title={item.name} description={`${item.sku} · ${item.package}`} actions={<><Button variant="secondary"><History className="size-4" />History</Button><Link to="/inventory/actions/new"><Button><ArrowRightLeft className="size-4" />Record action</Button></Link></>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="On hand" value={`${number(item.onHand)} ${item.baseUnit === "ml" ? "bottles eq." : item.baseUnit}`} detail={item.location} tone={tone(item.status)} /><StatCard label="Inventory value" value={money(item.value)} detail={`${money(item.cost)} current unit cost`} /><StatCard label="Par level" value={`${item.par} ${item.baseUnit === "ml" ? "bottles" : item.baseUnit}`} detail={item.onHand < item.par ? `${number(item.par - item.onHand)} below par` : `${number(item.onHand - item.par)} above par`} /><StatCard label="Status" value={item.status} detail="Based on active site policy" /></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_0.65fr]"><Card><CardHeader title="Location balances" description="Rebuildable projections from posted journal entries." /><TableShell><table className="data-table"><thead><tr><th>Location</th><th>Available</th><th>Last movement</th><th>Status</th></tr></thead><tbody><tr><td className="font-medium">{item.location}</td><td>{number(item.onHand)} {item.baseUnit}</td><td>Today, 9:42 AM</td><td><Badge tone={tone(item.status)}>{item.status}</Badge></td></tr><tr><td className="font-medium">Dry Store</td><td>{number(item.onHand * 0.35)} {item.baseUnit}</td><td>Yesterday</td><td><Badge tone="success">Available</Badge></td></tr></tbody></table></TableShell></Card><Card><CardHeader title="Item configuration" description="Current values; posted history retains snapshots." /><dl className="grid grid-cols-2 gap-x-4 gap-y-5 p-5 text-sm"><div><dt className="text-slate-500">Base unit</dt><dd className="mt-1 font-semibold">{item.baseUnit}</dd></div><div><dt className="text-slate-500">Package</dt><dd className="mt-1 font-semibold">{item.package}</dd></div><div><dt className="text-slate-500">Count method</dt><dd className="mt-1 font-semibold">{item.tare ? "Net weight + full count" : "Unit/package count"}</dd></div><div><dt className="text-slate-500">Tare / factor</dt><dd className="mt-1 font-semibold">{item.tare ? `${item.tare} g / ${item.factor}` : "Not required"}</dd></div></dl></Card></div>
  </div>;
}

export function StockActionPage() {
  const navigate = useNavigate();
  const { notify } = useApp();
  const [type, setType] = useState("Transfer");
  return <div className="mx-auto max-w-4xl page-grid"><Link to="/inventory" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Inventory</Link><PageHeader eyebrow="Inventory action" title="Record stock work" description="The posted action creates an immutable journal batch. Corrections use reversal entries." /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Action</span><Select className="w-full" value={type} onChange={(event) => setType(event.target.value)}><option>Transfer</option><option>Adjustment</option><option>Waste / loss</option><option>Opening balance</option></Select></label><label><span className="field-label">Item</span><Select className="w-full">{items.map((item) => <option key={item.id}>{item.name}</option>)}</Select></label><label><span className="field-label">From location</span><Select className="w-full"><option>Dry Store</option><option>Main Bar</option><option>Cold Store</option></Select></label><label><span className="field-label">To location</span><Select className="w-full" disabled={type !== "Transfer"}><option>Main Bar</option><option>Kitchen Prep</option><option>Service</option></Select></label><label><span className="field-label">Quantity</span><Input type="number" min="0" defaultValue="2" /></label><label><span className="field-label">Business date</span><Input type="date" defaultValue="2026-06-30" /></label><label className="sm:col-span-2"><span className="field-label">Reason</span><Input placeholder="Required explanation for the audit trail" defaultValue="Replenish Main Bar before service" /></label></div><div className="border-t p-5"><Notice title="Posting behavior">This prototype simulates one atomic journal batch. Production posting validates available stock, permissions, record version, and idempotency.</Notice><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => navigate(-1)}>Cancel</Button><Button onClick={() => { notify(`${type} saved to the prototype journal.`); navigate("/inventory"); }}><PackagePlus className="size-4" />Post {type.toLowerCase()}</Button></div></div></Card></div>;
}
