import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Download, Plus, Receipt, ShoppingCart, Trash2, Utensils } from "lucide-react";
import { items, purchaseRecords, usageRecords } from "../data/fixtures";
import { money } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Select, StatCard, TableShell } from "../components/ui";
import { useApp } from "../context/AppContext";

const statusTone = (status: string) => status === "Posted" ? "success" : status.includes("review") || status.includes("approval") ? "warning" : "neutral";

export function PurchasesPage() {
  return <div className="page-grid"><PageHeader eyebrow="Purchasing" title="Purchases and receiving" description="Ordering does not affect stock. Confirmed receiving creates the posted stock-in journal." actions={<><Button variant="secondary"><Download className="size-4" />Export</Button><Link to="/purchases/new"><Button><Plus className="size-4" />New receipt</Button></Link></>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Received this period" value={money(41230)} detail="2 posted receipts" tone="success" /><StatCard label="Needs review" value="1" detail="Produce receiving discrepancy" tone="warning" /><StatCard label="Open drafts" value="1" detail="Prime Cut Foods" /></div><Card><CardHeader title="Purchase records" description="Drafts, orders, and receiving records in one workspace." /><TableShell><table className="data-table"><thead><tr><th>Reference</th><th>Supplier</th><th>Date</th><th>Lines</th><th>Total</th><th>Status</th></tr></thead><tbody>{purchaseRecords.map((row) => <tr key={row.id}><td><Link className="font-semibold text-brand-600" to={`/purchases/${row.id}`}>{row.id}</Link></td><td>{row.supplier}</td><td>{row.date}</td><td>{row.lines}</td><td>{money(row.total)}</td><td><Badge tone={statusTone(row.status)}>{row.status}</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function PurchaseEditor() {
  const { purchaseId } = useParams();
  const navigate = useNavigate();
  const { notify } = useApp();
  const existing = purchaseRecords.find((row) => row.id === purchaseId);
  return <div className="mx-auto max-w-5xl page-grid"><Link to="/purchases" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Purchases</Link><PageHeader eyebrow={existing?.id ?? "New receipt"} title={existing ? existing.supplier : "Receive a purchase"} description="Verify what arrived, not only what was ordered." /><Card><div className="grid gap-5 p-5 sm:grid-cols-3"><label><span className="field-label">Supplier</span><Select className="w-full"><option>{existing?.supplier ?? "Metro Beverage Supply"}</option><option>Fresh Fields Produce</option></Select></label><label><span className="field-label">Invoice / reference</span><Input defaultValue={existing?.id ?? "INV-"} /></label><label><span className="field-label">Business date</span><Input type="date" defaultValue="2026-06-30" /></label></div><TableShell><table className="data-table"><thead><tr><th>Item</th><th>Package</th><th>Received</th><th>Unit cost</th><th>Amount</th><th /></tr></thead><tbody>{items.slice(0,3).map((item,index) => <tr key={item.id}><td className="font-semibold">{item.name}</td><td>{item.package}</td><td><Input className="w-24" type="number" defaultValue={index + 2} /></td><td><Input className="w-28" type="number" defaultValue={item.cost} /></td><td>{money(item.cost * (index + 2))}</td><td><Button variant="ghost" size="sm" aria-label={`Remove ${item.name}`}><Trash2 className="size-4" /></Button></td></tr>)}</tbody></table></TableShell><div className="border-t p-5"><Notice title="Posting creates stock">The document and stock-in journal batch are committed atomically. Later corrections create reversal entries.</Notice><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => notify("Purchase saved as draft.")}>Save draft</Button><Button onClick={() => { notify("Purchase posted to the prototype journal."); navigate("/purchases"); }}><Receipt className="size-4" />Post receipt</Button></div></div></Card></div>;
}

export function UsagePage() {
  return <div className="page-grid"><PageHeader eyebrow="Outbound activity" title="Usage and sales" description="Sales, recipes, non-revenue, waste, and production explain why stock left." actions={<Link to="/usage/new"><Button><Plus className="size-4" />Record usage</Button></Link>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Sales" value={money(48760)} detail="126 servings" tone="success" /><StatCard label="Non-revenue" value={money(3240)} detail="18 servings" /><StatCard label="Waste pending" value={money(1380)} detail="Owner approval required" tone="warning" /></div><Card><div className="flex gap-2 border-b p-4">{["All","Sales","Non-revenue","Waste","Production"].map((tab,index) => <Button key={tab} size="sm" variant={index ? "ghost" : "primary"}>{tab}</Button>)}</div><TableShell><table className="data-table"><thead><tr><th>Reference</th><th>Type</th><th>Source</th><th>Date</th><th>Quantity</th><th>Value</th><th>Status</th></tr></thead><tbody>{usageRecords.map((row) => <tr key={row.id}><td><Link className="font-semibold text-brand-600" to={`/usage/${row.id}`}>{row.id}</Link></td><td>{row.type}</td><td>{row.source}</td><td>{row.date}</td><td>{row.quantity}</td><td>{money(row.value)}</td><td><Badge tone={statusTone(row.status)}>{row.status}</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function UsageEditor() {
  const location = useLocation();
  const navigate = useNavigate();
  const { notify } = useApp();
  const editing = !location.pathname.endsWith("/new");
  return <div className="mx-auto max-w-4xl page-grid"><Link to="/usage" className="flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="size-4" />Usage & Sales</Link><PageHeader eyebrow={editing ? "Existing record" : "New outbound record"} title={editing ? "Waste record USE-2207" : "Record usage or sale"} description="Classify the business reason first; FNB/LIS creates the correct journal explanation." /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Activity type</span><Select className="w-full"><option>Direct sale</option><option>Recipe sale</option><option>Non-revenue</option><option>Waste / forfeit</option><option>Production</option></Select></label><label><span className="field-label">Business date</span><Input type="date" defaultValue="2026-06-30" /></label><label><span className="field-label">Item or recipe</span><Select className="w-full"><option>House Gin Sour · recipe v4</option>{items.map((item) => <option key={item.id}>{item.name}</option>)}</Select></label><label><span className="field-label">Quantity</span><Input type="number" min="0" defaultValue="2" /></label><label className="sm:col-span-2"><span className="field-label">Reason / source</span><Input defaultValue="Service breakage documented by shift lead" /></label></div><div className="border-t p-5"><Notice title="Recipe behavior">Recipe sales expand using the effective published version. The selected version and ingredient values are snapshotted.</Notice><div className="mt-5 flex justify-end gap-2"><Button variant="secondary">Save draft</Button><Button onClick={() => { notify("Usage record submitted."); navigate("/usage"); }}><Utensils className="size-4" />Submit record</Button></div></div></Card></div>;
}
