import { useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Bot, Building2, Check, Download, FileText, Lock, Search, Settings, ShieldCheck, UserPlus, Users } from "lucide-react";
import { activity, reportTrend } from "../data/fixtures";
import { useApp } from "../context/AppContext";
import { money } from "../lib/utils";
import { Badge, Button, Card, CardHeader, Input, Notice, PageHeader, Select, StatCard, TableShell } from "../components/ui";

const reportCards = [
  ["audit-reconciliation","Audit reconciliation","Beginning, activity, ending, and unexplained variance"],
  ["inventory-on-hand","Inventory on hand","Current balances, locations, cost, and par status"],
  ["inventory-valuation","Inventory valuation","Cost snapshots and value by category"],
  ["movements","Stock movements","Receipts, issues, transfers, and corrections"],
  ["purchases","Purchases","Supplier receiving, costs, and discrepancies"],
  ["usage","Usage & sales","Direct sales, recipes, non-revenue, and production"],
  ["waste","Waste and forfeits","Loss reasons, value, and approval evidence"],
  ["recipe-cost","Recipe cost","Ingredient cost, margin, and published versions"],
  ["imports","Import batches","Files, mappings, reviewers, and commit results"],
  ["user-activity","User activity","Sensitive actions and access evidence"]
];

export function ReportsPage() {
  return <div className="page-grid"><PageHeader eyebrow="Analysis" title="Reports" description="Decision-focused views backed by the same journal and posted source documents." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{reportCards.map(([key,title,detail]) => <Link key={key} to={`/reports/${key}`}><Card className="h-full p-5 transition hover:border-blue-300 hover:bg-blue-50/30"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-brand-600"><FileText className="size-5" /></span><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{detail}</p></Card></Link>)}</div></div>;
}

export function ReportViewer() {
  const { reportKey } = useParams();
  const meta = reportCards.find((row) => row[0] === reportKey) ?? reportCards[0];
  return <div className="page-grid"><PageHeader eyebrow="Reports" title={meta[1]} description={meta[2]} actions={<><Button variant="secondary"><Download className="size-4" />Excel</Button><Button><Download className="size-4" />PDF</Button></>} /><Card><div className="flex flex-wrap gap-3 border-b p-4"><label><span className="field-label">From</span><Input type="date" defaultValue="2026-06-21" /></label><label><span className="field-label">To</span><Input type="date" defaultValue="2026-06-28" /></label><label><span className="field-label">Site</span><Select><option>BGC Flagship</option></Select></label><Button className="self-end">Run report</Button></div><div className="grid gap-4 p-5 sm:grid-cols-3"><StatCard label="Physical depletion" value={money(93800)} detail="Beginning + receipts − ending" /><StatCard label="Explained" value={money(91960)} detail="Posted operational activity" tone="success" /><StatCard label="Variance" value={money(1840)} detail="2.0% · above threshold" tone="danger" /></div><div className="h-64 px-4 pb-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={reportTrend}><defs><linearGradient id="reportBlue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={0.3}/><stop offset="95%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="period" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false} tickFormatter={(value) => `₱${value / 1000}k`} /><Tooltip formatter={(value: number) => money(value)} /><Area type="monotone" dataKey="usage" stroke="#1d4ed8" fill="url(#reportBlue)" strokeWidth={2}/><Area type="monotone" dataKey="explained" stroke="#16a34a" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card><Notice title="Formula transparency">Report columns link to source documents and journal entries. Exported reports include filters, formula version, generated time, and actor.</Notice></div>;
}

export function ApprovalsPage() {
  const { approvals, decideApproval } = useApp();
  return <div className="page-grid"><PageHeader eyebrow="Control" title="Approvals" description="Only higher-risk work waits here. Routine permitted operations remain fast." /><Card><TableShell><table className="data-table"><thead><tr><th>Request</th><th>Requested by</th><th>Age</th><th>Risk</th><th>Status</th><th>Decision</th></tr></thead><tbody>{approvals.map((row) => <tr key={row.id}><td><Link to={`/approvals/${row.id}`} className="font-semibold text-brand-600">{row.title}</Link><small className="block text-slate-500">{row.detail}</small></td><td>{row.requestedBy}</td><td>{row.age}</td><td><Badge tone={row.risk === "High" ? "danger" : "warning"}>{row.risk}</Badge></td><td><Badge tone={row.status === "Pending" ? "info" : row.status === "Approved" ? "success" : "danger"}>{row.status}</Badge></td><td><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={row.status !== "Pending"} onClick={() => decideApproval(row.id,"Rejected")}>Reject</Button><Button size="sm" disabled={row.status !== "Pending"} onClick={() => decideApproval(row.id,"Approved")}>Approve</Button></div></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function ApprovalDetailPage() {
  const { approvalId } = useParams();
  const { approvals, decideApproval } = useApp();
  const row = approvals.find((item) => item.id === approvalId) ?? approvals[0];
  return <div className="mx-auto max-w-4xl page-grid"><PageHeader eyebrow={row.id} title={row.title} description={row.detail} /><div className="grid gap-5 lg:grid-cols-[1fr_0.55fr]"><Card><CardHeader title="Evidence" description="Review the proposed change and its effect." /><dl className="grid gap-5 p-5 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Requested by</dt><dd className="mt-1 font-semibold">{row.requestedBy}</dd></div><div><dt className="text-slate-500">Risk</dt><dd className="mt-1"><Badge tone={row.risk === "High" ? "danger" : "warning"}>{row.risk}</Badge></dd></div><div><dt className="text-slate-500">Current state</dt><dd className="mt-1 font-semibold">Draft / no journal effect</dd></div><div><dt className="text-slate-500">After approval</dt><dd className="mt-1 font-semibold">Posted and audit-visible</dd></div></dl></Card><Card className="p-5"><ShieldCheck className="size-8 text-brand-600" /><h2 className="mt-4 font-semibold">Decision</h2><p className="mt-2 text-sm text-slate-500">A reason is recorded with either decision.</p><Input className="mt-4" placeholder="Decision note" /><div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={() => decideApproval(row.id,"Rejected")}>Reject</Button><Button onClick={() => decideApproval(row.id,"Approved")}>Approve</Button></div></Card></div></div>;
}

export function AuditLogPage() {
  const { logId } = useParams();
  if (logId) return <div className="mx-auto max-w-4xl page-grid"><PageHeader eyebrow={logId} title="Import reviewed" description="IMP-308 · POS Daily Close" /><Card><CardHeader title="Audit evidence" description="Human context first; technical correlation remains available." /><dl className="grid gap-5 p-6 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Actor</dt><dd className="font-semibold">Carlo Reyes</dd></div><div><dt className="text-slate-500">Site</dt><dd className="font-semibold">BGC Flagship</dd></div><div><dt className="text-slate-500">Before</dt><dd className="font-semibold">2 unmatched rows</dd></div><div><dt className="text-slate-500">After</dt><dd className="font-semibold">All rows mapped</dd></div><div><dt className="text-slate-500">Device</dt><dd className="font-semibold">WEB-DEMO-01</dd></div><div><dt className="text-slate-500">Correlation</dt><dd className="font-mono text-xs">corr_imp_308_review</dd></div></dl></Card></div>;
  return <div className="page-grid"><PageHeader eyebrow="History" title="Audit log" description="Who did what, where, and why—linked to the resulting business and journal records." /><Card><div className="flex gap-3 border-b p-4"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400" /><Input className="pl-9" placeholder="Search actions, records, or actors…" /></div><Select><option>All actions</option><option>Sensitive only</option></Select></div><TableShell><table className="data-table"><thead><tr><th>Action</th><th>Record</th><th>Actor</th><th>When</th><th>Evidence</th></tr></thead><tbody>{activity.map((row) => <tr key={row.id}><td className="font-semibold">{row.action}</td><td>{row.subject}</td><td>{row.actor}</td><td>{row.time}</td><td><Link to={`/audit-log/${row.id}`} className="text-sm font-semibold text-brand-600">Inspect</Link></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function TeamPage() {
  const location = useLocation();
  const { memberId } = useParams();
  if (location.pathname.endsWith("/roles")) return <RoleMatrix />;
  if (memberId) return <div className="mx-auto max-w-3xl page-grid"><PageHeader eyebrow="Team member" title="Mia Santos" description="Staff · BGC Flagship" /><Card><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Role</span><Select className="w-full"><option>Staff</option><option>Owner</option><option>Auditor</option></Select></label><label><span className="field-label">Site access</span><Select className="w-full"><option>BGC Flagship</option></Select></label></div><div className="flex justify-end border-t p-5"><Button>Save access</Button></div></Card></div>;
  return <div className="page-grid"><PageHeader eyebrow="Access" title="Team" description="People, roles, site scope, and trusted sessions." actions={<><Link to="/team/roles"><Button variant="secondary"><Lock className="size-4" />Role matrix</Button></Link><Button><UserPlus className="size-4" />Invite user</Button></>} /><Card><TableShell><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Site scope</th><th>Last active</th><th>Status</th></tr></thead><tbody>{[["Lourd Borromeo","Owner","All sites","Now"],["Mia Santos","Staff","BGC Flagship","8 min ago"],["Ana Cruz","Auditor","BGC Flagship","Yesterday"]].map((row) => <tr key={row[0]}><td><Link to="/team/mia" className="font-semibold text-brand-600">{row[0]}</Link></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><Badge tone="success">Active</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

function RoleMatrix() {
  return <div className="page-grid"><PageHeader eyebrow="Access policy" title="Role matrix" description="Navigation, actions, fields, exports, and approvals derive from one central policy registry." /><Card><TableShell><table className="data-table"><thead><tr><th>Capability</th><th>Owner</th><th>Staff</th><th>Auditor</th></tr></thead><tbody>{[["View inventory",1,1,1],["Record routine work",1,1,0],["Close audit",1,0,0],["Commit import",1,0,0],["View cost and price",1,1,1],["Manage users",1,0,0]].map(([name,...values]) => <tr key={String(name)}><td className="font-semibold">{name}</td>{values.map((value,index) => <td key={index}>{value ? <Check className="size-4 text-emerald-600" /> : "—"}</td>)}</tr>)}</tbody></table></TableShell></Card></div>;
}

export function OrganizationPage() {
  const locations = useLocation().pathname.endsWith("/locations");
  return <div className="page-grid"><PageHeader eyebrow="Organization" title={locations ? "Locations" : "Sites"} description={locations ? "Storage, service, prep, and count areas within each site." : "Operational branches with isolated inventory and audit periods."} actions={<Button><Building2 className="size-4" />Add {locations ? "location" : "site"}</Button>} /><Card><TableShell><table className="data-table"><thead><tr><th>Name</th><th>Type</th><th>Scope</th><th>Inventory rows</th><th>Status</th></tr></thead><tbody>{(locations ? [["Main Bar","Service","BGC Flagship","42"],["Dry Store","Storage","BGC Flagship","55"],["Cold Store","Storage","BGC Flagship","28"],["Kitchen Prep","Prep","BGC Flagship","34"]] : [["BGC Flagship","Operational","5 locations","159"],["Makati Test Site","Training","2 locations","24"]]).map((row) => <tr key={row[0]}>{row.map((cell,index) => <td key={cell} className={index === 0 ? "font-semibold" : ""}>{cell}</td>)}<td><Badge tone="success">Active</Badge></td></tr>)}</tbody></table></TableShell></Card></div>;
}

export function SettingsPage() {
  const key = useLocation().pathname.split("/").pop() ?? "general";
  const title = key[0].toUpperCase() + key.slice(1);
  return <div className="page-grid"><PageHeader eyebrow="Settings" title={title} description="Defaults affect future work only; posted historical records retain their snapshots." /><div className="grid gap-5 lg:grid-cols-[220px_1fr]"><Card className="h-fit p-2">{["general","inventory","imports","security","integrations","privacy"].map((item) => <Link key={item} to={`/settings/${item}`} className={`block rounded-lg px-3 py-2.5 text-sm font-medium capitalize ${item === key ? "bg-blue-50 text-brand-700" : "text-slate-600 hover:bg-slate-50"}`}>{item}</Link>)}</Card><Card><CardHeader title={`${title} settings`} description="Tenant-level policy for BGC Flagship." /><div className="grid gap-5 p-6 sm:grid-cols-2"><label><span className="field-label">Primary policy</span><Select className="w-full"><option>Recommended default</option><option>Strict</option><option>Custom</option></Select></label><label><span className="field-label">Effective date</span><Input type="date" defaultValue="2026-07-01" /></label><label className="sm:col-span-2"><span className="field-label">Operational note</span><Input defaultValue="Changes are logged and apply only to future records." /></label></div><div className="flex justify-end border-t p-5"><Button><Settings className="size-4" />Save settings</Button></div></Card></div></div>;
}

export function StockyPage() {
  const [question,setQuestion] = useState("");
  const [messages,setMessages] = useState(["Ask about audit variance, stock history, imports, or how a formula works."]);
  return <div className="mx-auto max-w-4xl page-grid"><PageHeader eyebrow="Assistant" title="Stocky" description="Permission-aware answers with links to source records. Stocky cannot approve or post work." /><Card className="overflow-hidden"><div className="min-h-96 space-y-4 bg-slate-50 p-6">{messages.map((message,index) => <div key={index} className={`max-w-[80%] rounded-2xl p-4 text-sm leading-6 ${index ? "ml-auto bg-brand-600 text-white" : "rounded-tl-sm bg-white shadow-sm"}`}>{message}</div>)}</div><form className="flex gap-2 border-t p-4" onSubmit={(event) => { event.preventDefault(); if (!question) return; setMessages((current) => [...current, question, "I found relevant records in the June 28 audit. The largest open variance is Dark Rum; open Reconciliation to inspect its counts and posted usage."]); setQuestion(""); }}><Input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask Stocky…" /><Button type="submit"><Bot className="size-4" />Ask</Button></form></Card></div>;
}

export function HelpPage() {
  const { article } = useParams();
  if (article) return <div className="mx-auto max-w-3xl page-grid"><PageHeader eyebrow="Help article" title="How open-container counting works" description="A practical explanation of tare weight and remaining content." /><Card className="prose prose-slate max-w-none p-7"><p>Weigh the current container. FNB/LIS subtracts its configured empty-container weight, then applies the item-specific content factor.</p><pre className="mt-5 rounded-xl bg-slate-950 p-4 text-sm text-white">remaining = (scale weight - tare weight) × factor</pre><Notice title="Safety rule">A reading below tare is rejected. A result above capacity must be reviewed by an Owner.</Notice></Card></div>;
  return <div className="page-grid"><PageHeader eyebrow="Guidance" title="Help center" description="Workflow instructions, formula explanations, and troubleshooting." /><div className="relative"><Search className="absolute left-4 top-4 size-5 text-slate-400" /><Input className="min-h-12 pl-12" placeholder="Search help…" /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Run a complete audit","Count open containers","Review an import","Correct a posted record","Understand variance","Work offline"].map((title,index) => <Link key={title} to={index === 1 ? "/help/open-container-counting" : "/help/workflow"}><Card className="h-full p-5 hover:border-blue-300"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-slate-500">Step-by-step guidance and related system records.</p></Card></Link>)}</div></div>;
}
